### ISSUE TITLE
INSTALL and VERSION are missing in the sdist on PyPI

### ISSUE THREAD

**Issue by sunpoet** [levitsky/pyteomics#7]
setup.py reads INSTALL and README for long_description.
setup.py reads VERSION for version.
But both files (INSTALL and VERSION) are missing in the sdist on PyPI.

Here's the error message of build failure:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    with open('VERSION') as v:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
*** Error code 1

Stop.
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 12, in <module>
    with open('README.rst') as r, open('INSTALL') as i:
FileNotFoundError: [Errno 2] No such file or directory: 'INSTALL'
*** Error code 1

Stop.
```

**Comment by levitsky** [comment]
Ouch, sorry about that. I'm on it.

**Comment by sunpoet** [comment]
Thanks!
